[book]
authors = ["XUPEI"]
language = "en"
multilingual = false
src = "src"
title = "XUPEI's Playground"

[output.html.fold]
enable = true
level = 1
no-section-label = true

[preprocessor.katex]
after = ["links"]

[preprocessor.toc]
marker = "[TOC]"